name: nnunet_env_2
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip
  - pip:
      - -e nnUNet
